mongoid_options: &mongoid_options
  allow_dynamic_fields: false

development:
  sessions:
    default:
      database: slices_development
      hosts:
        - localhost:27017
      options:
        safe: true
  options:
    <<: *mongoid_options
test:
  sessions:
    default:
      database: slices_test
      hosts:
        - localhost:27017
      options:
        safe: true
        max_retries: 1
        retry_interval: 0
  options:
    <<: *mongoid_options
